#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_upgrade_idc.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_upgrade_ft8716.o
