name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: init
      run: git submodule init
    - name: pull
      run: git submodule update
    - name: configure
      run: make x86_64_cuttlefish_defconfig
    - name: make
      run: make cc=clang
